name: DevSecOps CI/CD Pipeline

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]
  workflow_dispatch: {}

# Hak akses minimal untuk GITHUB_TOKEN (prinsip least_privilege)
permissions:
  contents: read

jobs:
  # ==========================================
  # CI JOB 1: SAST Scan (Semgrep)
  # ==========================================
  sast-scan:
    name: Semgrep SAST Scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Run Semgrep SAST
        # --exclude=".github" mencegah Semgrep memeriksa file workflow YAML
        run: semgrep scan --config auto --error --verbose --exclude=".github"

  # ==========================================
  # CI JOB 2: Code Quality (Pylint)
  # ==========================================
  pylint-check:
    name: Pylint Code Quality Gate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r requirements.txt

      - name: Run Pylint Check
        run: pylint --fail-under=9.0 app.py

  # ==========================================
  # CI JOB 3: Secret Scan (Gitleaks)
  # ==========================================
  secret-scan:
    name: Gitleaks Secret Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ambil seluruh riwayat commit untuk analisis Gitleaks
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}

  # ==========================================
  # CI JOB 4: Dependency Scan (pip-audit)
  # ==========================================
  dependency-scan:
    name: Dependency Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run pip-audit
        run: |
          python -m pip install --upgrade pip
          pip install pip-audit
          pip-audit -r requirements.txt

  # ==========================================
  # CI JOB 5: Container Image Scan (Trivy)
  # ==========================================
  image-scan:
    name: Container Image Vulnerabiity Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Build Docker Image for Scanning
        run: docker build -t secure-flask-app:latest .

      - name: Run Trivy Scan
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:latest image \
            --severity HIGH,CRITICAL \
            --ignore-unfixed \
            --exit-code 1 \
            secure-flask-app:latest

  # ==========================================
  # CD STAGE: Deploy ke VM
  # ==========================================
  deploy-to-vm:
    name: Build & Deploy to VirtualBox VM
    needs: [sast-scan, pylint-check, secret-scan, dependency-scan, image-scan]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: self-hosted
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Build and Run Container
        run: |
          docker build -t secure-flask-app:latest .
          docker stop web-flask || true
          docker rm web-flask || true
          docker run -d -p 5000:5000 --name web-flask secure-flask-app:latest
          docker ps | grep web-flask
